# -*- coding: utf-8 -*-
"""Vigenere_Cipher.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QXPQDjdDHY1pZy0kPlOJFpJ5oz_ASDqa
"""

from ipywidgets import widgets, VBox, interact
from IPython.display import display

def vigenere_cipher(text, key, mode):
    result = ""
    key = key * (len(text) // len(key)) + key[:len(text) % len(key)]

    for i in range(len(text)):
        char = text[i]
        if char.isalpha():
            ascii_offset = ord('A') if char.isupper() else ord('a')
            key_shift = ord(key[i].upper()) - ord('A')

            if mode == 'Encrypt':
                result += chr((ord(char) + key_shift - ascii_offset) % 26 + ascii_offset)
            else:  # Decrypt
                result += chr((ord(char) - key_shift - ascii_offset) % 26 + ascii_offset)
        else:
            result += char
    return result

def on_button_click(b):
    result_text.value = vigenere_cipher(text_input.value, key_input.value, operation_dropdown.value)

text_input = widgets.Textarea(value='Enter text', description='Text:')

key_input = widgets.Text(value='KEY', description='Key:')

operation_dropdown = widgets.Dropdown(options=['Encrypt', 'Decrypt'], value='Encrypt', description='Operation:')

encrypt_button = widgets.Button(description='Encrypt/Decrypt')

result_text = widgets.Textarea(value='', description='Result:', disabled=True)

encrypt_button.on_click(on_button_click)

VBox([text_input, key_input, operation_dropdown, encrypt_button, result_text])